In [3]:
s = 2
a = [s] + [1]*5
print(*a)

2 1 1 1 1 1


In [2]:
[1] + [2]

[1, 2]

In [7]:
import torch
celoss = torch.nn.CrossEntropyLoss()
pred = torch.tensor([[0.1, 0.3, 0.6], [0.1, 0.8, 0.1], [0.1, 0.2, 0.7]])
labels = torch.tensor([0, 1, 2])
loss = celoss(pred, labels)
loss.shape

torch.Size([])

In [12]:
a = torch.Tensor([1])
b = torch.Tensor([2])
c = []
c.append(a)
c.append(b)
print(c)
d = torch.cat(c, dim=0)
print(d)

[tensor([1.]), tensor([2.])]
tensor([1., 2.])


In [4]:
import torch
import torch.nn.functional as F

noise_adaption = torch.nn.Parameter(torch.zeros(10, 9))
teacher_acc = torch.Tensor([0.7])
noise_adaption_softmax = F.softmax(noise_adaption, dim=1) * (1-teacher_acc)

noise_adaption_layer = torch.zeros(10, 10)

for i in range(10):
    #第一行
    if i == 0:
        noise_adaption_layer[i] = torch.cat([teacher_acc, noise_adaption_softmax[i][i:]])
    if i == 9:
        noise_adaption_layer[i] = torch.cat([noise_adaption_softmax[i][:i], teacher_acc])
    else:
        noise_adaption_layer[i] = torch.cat([noise_adaption_softmax[i][:i], teacher_acc, noise_adaption_softmax[i][i:]])

print(noise_adaption_layer)

tensor([[0.7000, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333,
         0.0333],
        [0.0333, 0.7000, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333,
         0.0333],
        [0.0333, 0.0333, 0.7000, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333,
         0.0333],
        [0.0333, 0.0333, 0.0333, 0.7000, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333,
         0.0333],
        [0.0333, 0.0333, 0.0333, 0.0333, 0.7000, 0.0333, 0.0333, 0.0333, 0.0333,
         0.0333],
        [0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.7000, 0.0333, 0.0333, 0.0333,
         0.0333],
        [0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.7000, 0.0333, 0.0333,
         0.0333],
        [0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.7000, 0.0333,
         0.0333],
        [0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.7000,
         0.0333],
        [0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333,
         0.7000]], grad_fn=<

In [6]:
import torch
from torchvision.datasets import CIFAR10, CIFAR100, ImageFolder
import torchvision.transforms as transforms
transform_train = transforms.Compose([
				transforms.RandomCrop(32, padding=4),
				transforms.RandomHorizontalFlip(),
				transforms.ToTensor(),
				transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010)),
				])

dataset_train = CIFAR10('/home/ubuntu/datasets', transform=transform_train, download=False)

In [4]:
import torch
a = torch.randn((2, 3, 4))
print(a)
print(a[:,:,1:])
print(a[:,:,:-1])

tensor([[[ 0.1346,  0.9274,  0.4694,  0.6224],
         [ 0.9558,  0.0269, -1.3040, -1.3778],
         [-0.5126, -0.4741,  0.3212,  0.6842]],

        [[ 1.2724, -0.3609,  0.2959,  1.5027],
         [ 0.0995,  1.5858, -0.6697,  0.2166],
         [-0.5268, -0.7467,  2.0048, -1.9143]]])
tensor([[[ 0.9274,  0.4694,  0.6224],
         [ 0.0269, -1.3040, -1.3778],
         [-0.4741,  0.3212,  0.6842]],

        [[-0.3609,  0.2959,  1.5027],
         [ 1.5858, -0.6697,  0.2166],
         [-0.7467,  2.0048, -1.9143]]])
tensor([[[ 0.1346,  0.9274,  0.4694],
         [ 0.9558,  0.0269, -1.3040],
         [-0.5126, -0.4741,  0.3212]],

        [[ 1.2724, -0.3609,  0.2959],
         [ 0.0995,  1.5858, -0.6697],
         [-0.5268, -0.7467,  2.0048]]])
